project_name: wswcli

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/wimwenigerkind/wswcli:latest"
      - "ghcr.io/wimwenigerkind/wswcli:{{ .Tag }}"
      - "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}"
      - "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
  - image_templates:
      - "ghcr.io/wimwenigerkind/wswcli:latest-arm64"
      - "ghcr.io/wimwenigerkind/wswcli:{{ .Tag }}-arm64"
      - "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}-arm64"
      - "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}.{{ .Minor }}-arm64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/wimwenigerkind/wswcli:latest"
    image_templates:
      - "ghcr.io/wimwenigerkind/wswcli:latest"
      - "ghcr.io/wimwenigerkind/wswcli:latest-arm64"
  - name_template: "ghcr.io/wimwenigerkind/wswcli:{{ .Tag }}"
    image_templates:
      - "ghcr.io/wimwenigerkind/wswcli:{{ .Tag }}"
      - "ghcr.io/wimwenigerkind/wswcli:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}"
    image_templates:
      - "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}"
      - "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/wimwenigerkind/wswcli:v{{ .Major }}.{{ .Minor }}-arm64"

brews:
  - name: wswcli
    description: "wswcli"
    homepage: "https://github.com/wimwenigerkind/wswcli"
    license: "MIT"
    repository:
      owner: wimwenigerkind
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    install: |
      bin.install "wswcli"
    test: |
      system "#{bin}/wswcli", "--version"